
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 04 16:38:38 IST 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 8;
  public static final int LCBR = 25;
  public static final int LTE = 31;
  public static final int SEMI = 22;
  public static final int CONTINUE = 7;
  public static final int INT = 17;
  public static final int MINUS = 32;
  public static final int LT = 30;
  public static final int LP = 21;
  public static final int COMMA = 6;
  public static final int CLASS = 5;
  public static final int RP = 20;
  public static final int PLUS = 23;
  public static final int MULTIPLY = 19;
  public static final int ASSIGN = 2;
  public static final int IF = 16;
  public static final int ID = 36;
  public static final int DOT = 9;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int LB = 24;
  public static final int LAND = 18;
  public static final int EQUAL = 10;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int LOR = 29;
  public static final int NUMBER = 35;
  public static final int MOD = 33;
  public static final int BREAK = 4;
  public static final int GTE = 15;
  public static final int ELSE = 12;
  public static final int NEQUAL = 34;
  public static final int CLASS_ID = 37;
  public static final int EXTENDS = 11;
  public static final int LNEG = 28;
  public static final int FALSE = 13;
  public static final int GT = 14;
  public static final int LENGTH = 26;
}

