
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
<<<<<<< HEAD
// Sat Nov 28 17:38:09 IST 2015
=======
// Thu Nov 26 21:52:05 IST 2015
>>>>>>> efe3ea8bd6df4e0ec5842b895e3593fa3bf62763
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class YcalcSym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int DIVIDE = 6;
  public static final int NUMBER = 9;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int ID = 10;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int TIMES = 5;
  public static final int LPAREN = 7;
}

